### ISSUE TITLE
AnimatorProxy NullPointerException

### ISSUE THREAD

**Issue by testasullaluna** [jouni/Animator#10]
Hi all,
I had an exception using AnimatorProxy as shown in the following:

Grave: Terminal error:
java.lang.NullPointerException
at org.vaadin.jouni.animator.AnimatorProxy.changeVariables(AnimatorProxy.java:170)
at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1460)
at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1404)
at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1329)
at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.doHandleUidlRequest(AbstractCommunicationManager.java:761)
at com.vaadin.terminal.gwt.server.CommunicationManager.handleUidlRequest(CommunicationManager.java:296)
at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:501)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at net.sf.ehcache.constructs.web.filter.GzipFilter.doFilter(GzipFilter.java:95)
at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:240)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:164)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:562)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:395)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:250)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:188)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:302)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

I tried to debug my application but it seems that it's all ok. 
Can anyone get me further information about the cause of this exception?

Thanks in advance

**Comment by log2** [comment]
This might be an issue with WeakHashMap<Integer,... > used in AninmatorProxy, till at least v1.6.6; in fact,that map should behave like a regular HashMap for the first 128 animation keys, since boxed versions of integers between -128 and +127 are always in memory and never garbage collected (see http://stackoverflow.com/questions/8873216/weakhashmap-doesnt-remove-obsolete-entries for a similar issue). Yet, keys generated beyond 128-animations limit should be Integers allocated via regular new Integer() call, though, so they might start to disappear (be gc-ed) and generating NPEs like the one you posted.

Could you please try to re-generate your AnimatorProxy, replacing old AP instance with a fresh, new one on a regular basis, say every 128 (or less) animations requested?

In this way, animation count in an AP instance should never reach a value sensitive to this gc problem, before that instance is replaced by a "fresh" one.

A dirty hack, indeed. ;-)

**Comment by rikuhaa** [comment]
Increasing the Integer-cache size really seems to have fixed the problem in my case (eg. -Djava.lang.Integer.IntegerCache.high=4096). Thanks for the info!

Even though using a lot larger Integer-cache if needed does not really make a much difference in our configuration, this solution seems a bit fragile. Is there any reason in the first place to use a WeakHashMap..? At least in my scenario and some quick testing the memory used by the AnimatorProxy does not really show up even when there is hundreds of animations added to it, and the map becomes garbage collectable anyway when the AnimatorProxy is detached (or at the very least when the Application instance is closed); or at least I don't see any weird things (like statics) going on that would prevent gc'ing it when it is not used anymore.

**Comment by jouni** [comment]
I'll have to confess, I don't really know why I've used WeakHashMap. I don't know if it will break anything if I change it to a regular HashMap?

**Comment by rikuhaa** [comment]
It should not break anything. 

WeakHashMap and HashMap should behave identically except for the case when there are no other references to certain key than the one in the map. In that case the key and the value associated with the key are removed from the WeakHashMap and the key-object (and possibly value-object) is garbage collected; with normal HashMap the fact that the key is referenced by the map would be enough to prevent the key from being garbage collected. As mentioned earlier, the only reason why the WeakHashMap-solution is working at all in the Animator, is that JVM always keeps around a cache of some likely to be frequently used Integer-objects.

Using Weak/Soft/Phantom-references is a tricky subject... Here is one article on WeakReferences if you are interested to learn more: http://www.ibm.com/developerworks/java/library/j-jtp11225/index.html . Basically you would never want to store data that you _need_ to keep around by weak-reference or as a key in WeakHashMap, they are usable only in more "advanced" use cases.

**Comment by jouni** [comment]
Changed to HashMap in 6e62bca34b0d80df70920db62f259840d149ceda
